### PR TITLE
Validate ~/.shoov.json exists.

### PR DESCRIPTION
**Pull request by nedSaf**
#3

### CODE REVIEW

**Comment by nedSaf** [comment]
When `.shoov.json` doesn't exist:
test

And will open the browser and redirect to `https://app.shoov.io/#/my-account`

**Comment by nedSaf** [comment]
PR is ready for code review.

**Comment by amitaibu** [comment]
Merged, thanks.

**Comment by nedSaf** [comment]
@amitaibu When the file doesn't exist, there's an error message but the build continues as normal, Is that ok ?

**Comment by amitaibu** [comment]
Yes, for now it's fine

**Pull request closed without merging**
